# config/meta.yml

meta_product_name: "ToCare"
meta_title: "TooCare - Nurse community for better care"
meta_description: "Faciliter la prise en charge des patients pour les infirmiers libéraux"
meta_image: "logo.png" # should exist in `app/assets/images/`
